name: gdb-static-pr-pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        build_type: ["build-with-python"]
        architecture: ["x86_64"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y wget

    - name: Build
      run: make ${{ matrix.build_type }}-${{ matrix.architecture }} -j$((`nproc`+1))
    - name: Pack
      run: make pack

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        files: build/artifacts/gdb-static*.tar.gz
